FROM microsoft/dotnet
MAINTAINER Uirel <uirel@gany.net>

#Mappings and ports
VOLUME ["/config"]

#Adding Custom files
ADD init/ /etc/my_init.d/
ADD services/ /etc/service/
RUN chmod -v +x /etc/service/*/run /etc/my_init.d/*.sh
