FROM microsoft/dotnet
MAINTAINER Uirel <uirel@gany.net>

# Install Pre Requisites
RUN apt-get -q update && \
apt-get install -qy wget libopus0 opus-tools libopus-dev unzip libav-tools rsync nano ca-certificates curl git libunwind8 libicu-dev

#Mappings and ports
VOLUME ["/config"]

#Clean Up
RUN apt-get autoclean -y; apt-get autoremove -y &&\
apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Adding Custom files
ADD init/ /etc/my_init.d/
ADD services/ /etc/service/
RUN chmod -v +x /etc/service/*/run /etc/my_init.d/*.sh
